apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy
on:
  workflow_dispatch:
    inputs:
      artifact-id:
        type: string
        required: true
      artifact-url:
        type: string
        required: true
      environment:
        type: string
        required: true
  workflow_call:
    inputs:
      artifact-id:
        type: string
        required: true
      artifact-url:
        type: string
        required: true
      environment:
        type: string
        required: true

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: cloudbees-io/checkout@v2
        with:
          repository: https://github.com/cb-pov-tu5Ei/ecommerce
      - name: run ansible playbook
        uses: https://github.com/cb-pov-tu5Ei/ecommerce/.cloudbees/actions/run-ansible
        with:
          artifact-url: ${{ inputs.artifact-url }}
          environment: ${{ inputs.environment }}
